# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi machine configuration

servers=[
      {
        :hostname => "master",
        :ip => "192.168.33.101",
        :box => "debian/jessie64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "peer1",
        :ip => "192.168.33.102",
        :box => "debian/jessie64",
        :ram => 1024,
        :cpu => 2
      },
      {
        :hostname => "peer2",
        :ip => "192.168.33.103",
        :box => "debian/jessie64",
        :ram => 1024,
        :cpu => 2
      },
      {
        :hostname => "head1",
        :ip => "192.168.33.104",
        :box => "debian/jessie64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "head2",
        :ip => "192.168.33.105",
        :box => "debian/jessie64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "head3",
        :ip => "192.168.33.106",
        :box => "debian/jessie64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "deployment1",
        :ip => "192.168.33.107",
        :box => "debian/jessie64",
        :ram => 256,
        :cpu => 1
      },
      {
        :hostname => "uf1",
        :ip => "192.168.33.108",
        :box => "debian/jessie64",
        :ram => 256,
        :cpu => 1
      }
]

Vagrant.configure(2) do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true

    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|

            node.vm.box = "debian/jessie64"
            config.ssh.insert_key = false
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]

            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
                vb.name = machine[:hostname]
            end
        end

    end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    #ansible.inventory_path = "ansible_inventory"
    #ansible.host_key_checking = false
    #ansible.verbose = "v"
  end

end