# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi machine configuration

servers=[
      {
        :hostname => "master",
        :ip => "172.28.128.100",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "peer1-site1",
        :ip => "172.28.128.101",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "peer2-site1",
        :ip => "172.28.128.102",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "peer1-site2",
        :ip => "172.28.128.103",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "peer2-site2",
        :ip => "172.28.128.104",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "head1",
        :ip => "172.28.128.105",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "head2",
        :ip => "172.28.128.106",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "head3",
        :ip => "172.28.128.107",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "deployment1-site1",
        :ip => "172.28.128.108",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "deployment1-site2",
        :ip => "172.28.128.109",
        :box => "ubuntu/trusty64",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "uf1-site1",
        :ip => "172.28.128.110",
        :box => "ubuntu/trusty64",
        :ram => 256,
        :cpu => 1
      },
      {
        :hostname => "uf1-site2",
        :ip => "172.28.128.111",
        :box => "ubuntu/trusty64",
        :ram => 256,
        :cpu => 1
      }
]

Vagrant.configure(2) do |config|

    config.vm.synced_folder ".", "/vagrant", disabled: true

    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|

            node.vm.box = "ubuntu/trusty64"
            config.ssh.insert_key = false
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]

            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
                vb.name = machine[:hostname]
            end
        end

    end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "playbook.yml"
    #ansible.inventory_path = "ansible_inventory"
    #ansible.host_key_checking = false
    #ansible.verbose = "v"
  end

end