# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant multi machine configuration

servers=[
      {
        :hostname => "splunk",
        :ip => "172.28.128.100",
        :box => "ubuntu/trusty64",
        :ram => 2048,
        :cpu => 4
      },
      {
        :hostname => "dc-uk-lpsrv01",
        :box => "ubuntu/trusty64",
        :ip => "172.28.128.101",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "dc-uk-lpsrv02",
        :box => "ubuntu/trusty64",
        :ip => "172.28.128.102",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "dc-us-lpsrv01",
        :box => "ubuntu/trusty64",
        :ip => "172.28.128.103",
        :ram => 512,
        :cpu => 1
      },
      {
        :hostname => "dc-us-lpsrv02",
        :box => "ubuntu/trusty64",
        :ip => "172.28.128.104",
        :ram => 512,
        :cpu => 1
      }
]

Vagrant.configure(2) do |config|

    # Get's honored normally
    config.vm.synced_folder ".", "/vagrant", disabled: true
    # But not the centos box
    config.vm.synced_folder '.', '/home/vagrant/sync', disabled: true

    servers.each do |machine|

        config.vm.define machine[:hostname] do |node|

            node.vm.box = "ubuntu/trusty64"
            config.ssh.insert_key = false
            node.vm.usable_port_range = (2200..2250)
            node.vm.hostname = machine[:hostname]
            node.vm.network "private_network", ip: machine[:ip]

            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram], "--cpus", machine[:cpu]]
                vb.name = machine[:hostname]
            end
        end

    end

  config.vm.provision "ansible" do |ansible|
    ansible.limit = "all"
    ansible.playbook = "main.yml"
    #ansible.inventory_path = "ansible_inventory"
    #ansible.host_key_checking = false
    #ansible.verbose = "v"
  end

end